@devtunnel = https://dhqxlmt6-7245.euw.devtunnels.ms

GET {{devtunnel}}/todoitems

###

POST {{devtunnel}}/todoitems
Content-Type: application/json

{
  "head": "Walk cat",
  "body": "In the rain",
  "completed": false
}

###

GET {{devtunnel}}/todoitems/1

###

PUT {{devtunnel}}/todoitems/1
Content-Type: application/json

{
  "head": "xxxx",
  "body": "yyy",
  "completed": true
}

###

DELETE {{devtunnel}}/todoitems/1